dbe/dbe/forum/urls.py
# from django.conf.urls.defaults import *
from django.conf.urls import *
from django.contrib.auth.decorators import login_required as LR
from dbe.forum.models import *
from dbe.forum.views import *

urlpatterns = patterns("dbe.forum.views",
    (r"^forum/(?P<dpk>\d+)/$"             , ForumView.as_view(), {}, "forum"),
    (r"^thread/(?P<dpk>\d+)/$"            , ThreadView.as_view(), {}, "thread"),

    (r"^new_topic/(?P<dpk>\d+)/$"          , LR(NewTopic.as_view()), {}, "new_topic"),
    (r"^reply/(?P<dpk>\d+)/$"              , LR(Reply.as_view()), {}, "reply"),
    (r"^profile/(?P<mfpk>\d+)/$"           , LR(EditProfile.as_view()), {}, "profile"),

    (r""                                   , Main.as_view(), {}, "forum_main"),
)

dbe/dbe/urls.py
from django.conf.urls import patterns, include, url
# from django.conf.urls.defaults import *
from django.conf.urls import *
from django.contrib.auth.decorators import login_required as LR
from dbe.forum.models import *
from dbe.forum.views import *

# from django.contrib import admin
# admin.autodiscover()

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'dbe.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    # url(r'^admin/', include(admin.site.urls)),
    # url(r'^admin/', include(admin.site.urls)),
    url(r'^admin/', include(admin.site.urls)),        
)

urlpatterns += patterns("dbe.forum.views",
    (r"^forum/(?P<dpk>\d+)/$"             , ForumView.as_view(), {}, "forum"),
    (r"^thread/(?P<dpk>\d+)/$"            , ThreadView.as_view(), {}, "thread"),

    (r"^new_topic/(?P<dpk>\d+)/$"          , LR(NewTopic.as_view()), {}, "new_topic"),
    (r"^reply/(?P<dpk>\d+)/$"              , LR(Reply.as_view()), {}, "reply"),
    (r"^profile/(?P<mfpk>\d+)/$"           , LR(EditProfile.as_view()), {}, "profile"),
    (r"^$"                                 , Main.as_view(), {}, "forum_main"),
    # (r""                                   , Main.as_view(), {}, "forum_main"),
)

dbe/dbe/forum/models.py
from django.db.models import *
from django.contrib.auth.models import User
from django.contrib import admin
from django.db.models.signals import post_save

from dbe.settings import MEDIA_URL
from dbe.shared.utils import *


class Forum(BaseModel):
    title = CharField(max_length=60)

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse2("forum", dpk=self.pk)

    def num_posts(self):
        return sum([t.num_posts() for t in self.threads.all()])

    def last_post(self):
        """Go over the list of threads and find the most recent post."""
        threads = self.threads.all()
        last    = None
        for thread in threads:
            lastp = thread.last_post()
            if lastp and (not last or lastp.created > last.created):
                last = lastp
        return last


class Thread(BaseModel):
    title   = CharField(max_length=60)
    created = DateTimeField(auto_now_add=True)
    creator = ForeignKey(User, blank=True, null=True)
    forum   = ForeignKey(Forum, related_name="threads")

    class Meta:
        ordering = ["-created"]

    def __unicode__(self):
        return unicode("%s - %s" % (self.creator, self.title))

    def get_absolute_url(self) : return reverse2("thread", dpk=self.pk)
    def last_post(self)        : return first(self.posts.all())
    def num_posts(self)        : return self.posts.count()
    def num_replies(self)      : return self.posts.count() - 1


class Post(BaseModel):
    title   = CharField(max_length=60)
    created = DateTimeField(auto_now_add=True)
    creator = ForeignKey(User, blank=True, null=True)
    thread  = ForeignKey(Thread, related_name="posts")
    body    = TextField(max_length=10000)

    class Meta:
        ordering = ["created"]

    def __unicode__(self):
        return u"%s - %s - %s" % (self.creator, self.thread, self.title)

    def short(self):
        created = self.created.strftime("%b %d, %I:%M %p")
        return u"%s - %s\n%s" % (self.creator, self.title, created)

    def profile_data(self):
        p = self.creator.profile
        return p.posts, p.avatar


class UserProfile(BaseModel):
    avatar = ImageField("Profile Pic", upload_to="images/", blank=True, null=True)
    posts  = IntegerField(default=0)
    user   = OneToOneField(User, related_name="profile")

    def __unicode__(self):
        return unicode(self.user)

    def increment_posts(self):
        self.posts += 1
        self.save()

    def avatar_image(self):
        return (MEDIA_URL + self.avatar.name) if self.avatar else None

dbe/dbe/forum/forms.py
from django.forms import ModelForm
from dbe.forum.models import *
from dbe.shared.utils import ContainerFormMixin

class ProfileForm(ModelForm):
    class Meta:
        model   = UserProfile
        exclude = ["posts", "user"]

class PostForm(ContainerFormMixin, ModelForm):
    class Meta:
        model   = Post
        exclude = ["creator", "thread"]

dbe/dbe/forum/views.py
# Imports {{{
from PIL import Image as PImage

from dbe.settings import MEDIA_URL
from dbe.forum.models import *
from dbe.shared.utils import *

from dbe.mcbv.detail import DetailView
from dbe.mcbv.edit import CreateView, UpdateView
from dbe.mcbv.list_custom import ListView, ListRelated

from forms import ProfileForm, PostForm
# }}}


class Main(ListView):
    list_model    = Forum
    template_name = "forum/list.html"

class ForumView(ListRelated):
    detail_model  = Forum
    list_model    = Thread
    related_name  = "threads"
    template_name = "forum.html"

class ThreadView(ListRelated):
    list_model    = Post
    detail_model  = Thread
    related_name  = "posts"
    template_name = "thread.html"


class EditProfile(UpdateView):
    form_model      = UserProfile
    modelform_class = ProfileForm
    success_url     = '#'
    template_name   = "profile.html"

    def modelform_valid(self, modelform):
        """Resize and save profile image."""
        # remove old image if changed
        name = modelform.cleaned_data.get("avatar")
        pk   = self.kwargs.get("mfpk")
        old  = UserProfile.obj.get(pk=pk).avatar

        if old.name and old.name != name:
            old.delete()

        # save new image to disk & resize new image
        self.modelform_object = modelform.save()
        if self.modelform_object.avatar:
            img = PImage.open(self.modelform_object.avatar.path)
            img.thumbnail((160,160), PImage.ANTIALIAS)
            img.save(img.filename, "JPEG")
        return redir(self.success_url)


class NewTopic(DetailView, CreateView):
    detail_model    = Forum
    form_model      = Post
    modelform_class = PostForm
    title           = "Start New Topic"
    template_name   = "forum/post.html"

    def get_thread(self, modelform):
        title = modelform.cleaned_data.title
        return Thread.obj.create(forum=self.get_detail_object(), title=title, creator=self.user)

    def modelform_valid(self, modelform):
        """Create new thread and its first post."""
        data   = modelform.cleaned_data
        thread = self.get_thread(modelform)

        Post.obj.create(thread=thread, title=data.title, body=data.body, creator=self.user)
        self.user.profile.increment_posts()
        return redir(self.get_success_url())

    def get_success_url(self):
        return self.get_detail_object().get_absolute_url()


class Reply(NewTopic):
    detail_model = Thread
    title        = "Reply"

    def get_thread(self, modelform):
        return self.get_detail_object()

    def get_success_url(self):
        return self.get_detail_object().get_absolute_url() + "?page=last"


def forum_context(request):
    return dict(media_url=MEDIA_URL)

dbe/dbe/templates/blog/bbase.html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <title>{% block title %}Blog{% endblock %}</title>
    {% block extrahead %}{% endblock %}
    <link rel="stylesheet" href="/media/css/blog.css" type="text/css" media="screen" charset="utf-8" />

</head>

<body>

    <!-- SIDEBAR -->
    <div id="sidebar"> {% block sidebar %}{% endblock %} </div>

    <div id="container">

        <!-- MENU -->

        <div id="menu">
            {% block nav-global %}

                <h3>MyBlog</h3>
                {% if user.is_staff %}
                    <a href="{% url 'admin:index' %}">Admin</a>
                    <a href="{% url 'admin:blog_post_add' %}">Add post</a>
                {% endif %}

            {% endblock %}
        </div>

        <!-- CONTENT -->

        <div id="content">
            {% block content %}{% endblock %}
        </div>
    </div>

</body>
</html>

dbe/dbe/templates/blog/list.html
{% extends "blog/bbase.html" %}

{% block extrahead %}
    <link rel="stylesheet" href="/media/css/blog.css" type="text/css" media="screen" charset="utf-8" />
{% endblock %}

<!-- SIDEBAR -->

{% block sidebar %}
    <div id="sidebar">
        Monthly Archive
        <p>
        {% for ym in view.months %}
            {% ifchanged ym.0 %} {{ ym.0 }} <br /> {% endifchanged %}
            <a href="{% url 'archive_month' ym.0 ym.1 %}">{{ ym.2 }}</a> <br />
        {% endfor %}
        </p>
    </div>
{% endblock %}

<!-- LIST OF POSTS -->

{% block content %}
    <div class="main">
            {% for post in post_list %}
                <div class="title">{{ post.title }}</div>
                <ul>
                    <div class="time">{{ post.created }}</div>
                    <div class="body">{{ post.body|linebreaks }}</div>
                    <div class="commentlink">
                        <a href="{% url 'post' post.pk %}">Comments ({{ post.comments.count }})</a>
                    </div>
                </ul>
            {% endfor %}

        {% include "paginator.html" %}
    </div>
{% endblock %}

dbe/dbe/templates/blog/post.html
{% extends "blog/bbase.html" %}
{% block content %}
    <div class="main">

        <div class="title">{{ post.title }}</div>
        <ul>
            <div class="time">{{ post.created }}</div>
            <div class="body">{{ post.body|linebreaks }}</div>
        </ul>

        <hr />

        {% for comment in comment_list %}
            <ul>
                <div class="time">{{ comment.author }}</div>
                <div class="body">{{ comment.body|linebreaks }}</div>
            </ul>
        {% endfor %}


        <div id="reply">
        <form action="" method="POST"> {% csrf_token %}
            <table>
                {{ modelform.as_table }}
            </table>
            <input type="submit" value="Submit" />
        </form>
        </div>
    </div>
{% endblock %}

dbe/dbe/templates/bombquiz/bqbase.html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <title>{% block title %}BombQuiz{% endblock %}</title>
    <link rel="stylesheet" href="/media/css/quest.css" type="text/css" media="screen" charset="utf-8" />
    {% block extrahead %}{% endblock %}
</head>

<body {% block bodyattr %}{% endblock %}>
    <div id="container">

        <!-- MENU -->

        <div id="menu">
            {% block nav-global %}
                <h3>BombQuiz</h3>
                <a href="{% url 'new_player' %}">Start</a>
                <a href="{% url 'stats' %}">Stats</a>
                <a href="{% url 'admin:bombquiz_question_changelist' %}">BombQuiz Admin</a>
            {% endblock %}
        </div>

        <!-- CONTENT -->

        <div id="content">
            {% block content %}{% endblock %}
        </div>
    </div>

</body>
</html>

dbe/dbe/templates/bombquiz/done.html
{% extends "bqbase.html" %}
{% block content %}
    <div class="main">
        {% if view.request.session.left <= 0 %}
            <pre>
            　　　／ ,,-",-''i|　　￣|i''-､　　ヾ　　　{
　　　　　　　　 （"　　.／ 　 i　{;;;;;;;i|　　　 .|i;;;;;;）　,ノ　　　 ii
　　　　 ,,　　　　　　 （　　　 l,　`'-i|　　　　|i;;-'　　　　 ,,-'"　　　_,,-"
　　　　　"'-,,　　　　　`-,,,,-'--'':::￣:::::::''ニ;;-==,_____　'"　　_,,--''"
　　　　　　　 ￣"''-- _-'':::::"￣::::::::::::::::;;;;----;;;;;;;;::::`::"''::---,,_　　__,,-''"
　　　　　　　　._,,-'ニ-''ニ--''"￣.i|￣　　　|i-----,,￣`"''-;;::''-`-,,
　　　　　　,,-''::::二-''"　　　　 .--i|　　　　 .|i　　　　　　　　　 "- ;;:::`､
　　　　._,-"::::／　　　￣"''---　 i|　　　　　|i　　　　　　　　　　　　ヽ::::i
　　　 .（:::::{:（i(____　　　　　　　　 i|　　　　　.|i　　　　　　　　　　_,,-':/:::}
　　　　 `''-,_ヽ:::::''- ,,__,,,,　_______i|　　　　　 .|i--__,,----..--'''":::::ノ,,-'
　　　　　　　"--;;;;;;;;;;;;;;;;;""''--;;i|　　　　　　.|i二;;;;;::---;;;;;;;::--''"~
　　　　　　　　　　　　　 ￣￣"..i|　　　　 　　.|i
　　　　　　　　　　　　　　　　　.i|　　　　　　　 |i
　　　　　　　　　　　　　　　　　i|　　　　　　　　|i
　　　　　　　　　　　　　　　　 .i|　　 　 　　　　 .|i
　　　　　　　　　　　　　　　　 i|　　　　　　　　　|i
　　　　　　　　　　　　　　　 .i|　　　　 　　　　　　|i
　　　　　　　　　　　　　　　.i|　　　　　　,,-､　､　　|i
　　　　　　　　　　　　　　 i|　　　　　　ノ::::i:::トiヽ､_.|i
　　　　　　　　　　　_,,　　i|/"ヽ／:iヽ!::::::::ﾉ:::::Λ::::ヽ|i__n､ト､
　　　　　,,／^ヽ,-''":::i／::::::::／:::::|i／;;;;;;/::::;;;;ノ⌒ヽノ::::::::::::ヽ,_Λ
　　　　　;;;;;;:::::;;;;;;;;;;:::::;;;;;;;;:::/;;;;;;:::::::::;;;;;;/;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:::::::::::;;:;;;;:::ヽ
            </pre>
        {% else %}
            You've disabled the bomb and won the game!!
        {% endif %}
        <p><a href="{% url 'new_player' %}">back to main page</a></p>
    </div>
{% endblock %}

dbe/dbe/templates/bombquiz/newplayer.html
{% extends "bqbase.html" %}

{% block content %}
<div class="main">

    <form action="" method="POST">{% csrf_token %}
        <fieldset class="module">

        {{ modelform.non_field_errors }}
        {% for fld in modelform %}
            <div class="form-row">
                <label class="{% if fld.field.required %} required {% endif %}">
                    {{ fld.help_text }} {{ fld.name }}
                </label>
                {{ fld }} {{ fld.errors }}
            </div>
        {% endfor %}

        </fieldset>
        <div id="submit"><input id="submit-btn" type="submit" value="Continue"></div>
    </form>
</div>
{% endblock %}

dbe/dbe/templates/bombquiz/question.html
{% extends "bqbase.html" %}

{% block extrahead %}
    <SCRIPT type="text/javascript">
        window.history.forward();
        function noBack() { window.history.forward(); }
    </SCRIPT>
{% endblock %}
{% block bodyattr %}
onload="noBack();" onpageshow="if (event.persisted) noBack();" onunload=""
{% endblock %}

{% block content %}
<div class="main">

    {% if left %}
        <h2>BOMB</h2> 0:{{ left }} left <h2>BOMB</h2>
    {% endif %}

    <form action="" method="POST">{% csrf_token %}
        <fieldset class="module">

        {{ form.non_field_errors }}
        {% for fld in form %}
            <div class="form-row">
                <label class="{% if fld.field.required %} required {% endif %}">
                    {{ fld.help_text }}
                </label>
                {{ fld }} {{ fld.errors }}
            </div>
        {% endfor %}

        </fieldset>
        <div id="submit"><input id="submit-btn" type="submit" value="Continue"></div>
    </form>

    {% if qnum %} <p>{{ qnum }} of {{ total }}</p> {% endif %}
</div>
{% endblock %}

dbe/dbe/templates/bombquiz/stats.html
{% extends "bqbase.html" %}
{% block content %}
    <div class="main">
    <p>Average num of answers for failed players: {{ ans_failed.avg|floatformat:2 }}</p>
    </div>
{% endblock %}

dbe/dbe/templates/forum/fbase.html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <title>{% block title %}ForumApp{% endblock %}</title>
    {#<link rel="stylesheet" href="/media/css/forum.css" type="text/css" media="screen" charset="utf-8" />#}
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static "css/forum.css" %}" type="text/css" media="screen" charset="utf-8" />
</head>

<body>
    <div id="container">
        <div id="menu">
            {% block nav-global %}
                <h3><a id="homelink" href="{% url 'forum_main' %}">ForumApp</a></h3>

                <!-- MENU -->
                {% if user.is_staff %} <a href="{% url 'admin:index' %}">Admin</a> {% endif %}
                {% if user.is_authenticated %}
                    <a href="{% url 'profile' user.profile.pk %}">Edit profile</a>
                    <a href="/accounts/logout/?next=/forum/">logout</a>
                {% else %}
                    <a href="/accounts/login/?next=/forum/">login</a> <a href="/accounts/register/">register</a>
                {% endif %}

            {% endblock %}
        </div>

        <div id="content"> {% block content %}{% endblock %} </div>
    </div>

</body>
</html>

dbe/dbe/templates/forum/forum.html
{% extends "fbase.html" %}

{% block content %}
    <div class="main">

    <a id="new_topic" class="buttont" href="{% url 'new_topic' forum.pk %}">Start New Topic</a>
    <br /> <br />

    <div id="list">
        {% if thread_list %}
            <table border="0" cellpadding="4" width="100%">
              <tr>
                  <td>Topics</td>
                  <td>Replies</td>
                  <td>Last post</td>
                  <td></td>
              </tr>

              <!-- Threads  -->

              {% for thread in thread_list %}
              <tr {% if forloop.last %}class="last"{% endif %}>
                  <td>
                    <div class="title"><a href="{% url 'thread' thread.pk %}">{{ thread.title }}</a></div>
                  </td>
                  <td>{{ thread.num_replies }}</td>
                  <td>{{ thread.last_post.short|linebreaksbr }}</td>
                  <td><a class="button" href="{% url 'thread' thread.pk %}">VIEW</a></td>
              </tr>
              {% endfor %}

            </table>
        {% else %}
            <blockquote>No threads in this forum yet..</blockquote>
        {% endif %}
        </div>

        {% include "paginator.html" %}
    </div>
{% endblock %}

dbe/dbe/templates/forum/list.html
{% extends "fbase.html" %}

{% block content %}
    <div class="main">

        <div id="list">
        <table border="0" cellpadding="4" width="100%">
            <tr>
                <td></td>
                <td>Posts</td>
                <td>Last post</td>
                <td></td>
            </tr>

            <!-- List of forums -->

            {% for forum in forum_list %}
            <tr {% if forloop.last %}class="last"{% endif %}>
                <td>
                    <div class="title"><a href="{% url 'forum' dpk=forum.pk %}">{{ forum.title }}</a></div>
                </td>
                <td>{{ forum.num_posts }}</td>
                <td>{{ forum.last_post.short|linebreaksbr }}</td>
                <td><a class="button" href="{% url 'forum' dpk=forum.pk %}">VIEW</a></td>
            </tr>

            {% endfor %}
        </div>

    </div>

{% endblock %}

dbe/dbe/templates/forum/post.html
{% extends "fbase.html" %}
{% block content %}
    <div class="main">
        <div id="reply">
        <form action="" method="POST"> {% csrf_token %}
            <table>
                {{ modelform.as_table }}
            </table>
            <input type="submit" value="Submit" />
        </form>
        </div>
    </div>
{% endblock %}

dbe/dbe/templates/forum/profile.html
{% extends "fbase.html" %}

{% block content %}
    <div class="main">
        <div id="rtitle">Edit Profile</div><br />

        <p>
            <form enctype="multipart/form-data" action="" method="POST"> {% csrf_token %}

                {% if userprofile.avatar_image %}
                    <p><img border="0" alt="Profile Pic" src="{{ userprofile.avatar_image }}" /></p>
                {% endif %}

                {{ modelform.avatar }}
                <input type="submit" value="Submit" id="submit" />
            </form>
        </p>
    </div>

{% endblock %}

dbe/dbe/templates/forum/thread.html
{% extends "fbase.html" %}

{% block content %}
    <div class="main">

        <!-- Title and backlink -->

        <div class="ttitle">{{ thread.title }}</div>
        <div id="back">
            <a href="{% url 'forum' thread.forum.pk %}">&lt;&lt; back to list of topics</a>
        </div>


        <!-- Posts  -->

        <div id="list">
            {% for post in post_list %}
                <div class="post">

                    <!-- Profile pic and info -->

                    <div class="ppic">
                        {% with post.profile_data as pdata %}
                            {% if pdata.1 %}
                                <img src="{{ media_url }}{{ pdata.1 }}" /> <br />
                            {% endif %}
                        {{ post.creator }}<br />
                        Posts: {{ pdata.0 }}<br />
                        Joined: {{ post.creator.date_joined|date:"M d Y" }}
                        {% endwith %}
                    </div>

                    <!-- Title, author and body -->

                    <span class="title">{{ post.title }}</span><br />
                    by {{ post.creator }} | <span class="date">{{ post.created }}</span> <br /><br />

                    {{ post.body|linebreaksbr }} <br />
                    <div class="clear"></div>

                </div>
            {% endfor %}
        </div>

        <!-- Paginator and reply link -->

        {% include "paginator.html" %}
        <br />
        <a class="button" href="{% url 'reply' thread.pk %}">Reply</a>

    </div>

{% endblock %}

dbe/dbe/templates/index.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="{{ LANGUAGE_CODE }}" xml:lang="{{ LANGUAGE_CODE }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
<head>
    <title>{% block title %}DBE{% endblock %}</title>
    {% block extrastyle %}{% endblock %}
    {% block extrahead %}{% endblock %}
    {% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE" />{% endblock %}
</head>
{% load i18n %}

<body>

<h1>DBE</h1>
<div class="main_separator"></div>

<ul>
    <li><a href='/admin/'>admin</a></li>
    <li><a href='/blog/'>Blog</a></li>
    <li><a href='/bombquiz/'>Bombquiz</a></li>
    <li><a href='/forum/'>Forum</a></li>
    <li><a href='/admin/issues/issue/'>Issues</a></li>
    <li><a href='/portfolio/'>Portfolio</a></li>
    <li><a href='/questionnaires/'>Questionnaires</a></li>

    <li><a href='/sb/'>SB</a></li>
</ul>

</body>
</html>

dbe/dbe/templates/issues/add_issues.html
{% extends "issbase.html" %}
{% load todo %}

{% block extrahead %}
    <style type="text/css" media="screen">
        #container { width: 950px; }
        #content { width: 1300px; }
        td.itemrow { border-bottom: 3px solid #ccc; }
        .clear { clear: both; padding-bottom: 5px; }
        .module { width: 950px; }
    </style>
{% endblock %}

{% block content %}
<div class="main">
    <form action="" method="POST">{% csrf_token %}
    <div id="submit"><input id="submit-btn" type="submit" value="Save"></div>
    <div class="clear"></div>
        {{ formset.management_form }}

        <!-- FOR EACH FORM -->
        {% for form in formset %}
            <fieldset class="module aligned">
                {{ form.id }}

                <!-- FOR EACH FIELD -->
                {% for fld in form %}
                    <div class="form-row">
                        <label class="{% if fld.field.required %} required {% endif %}">{{ fld.label }}</label>
                        {{ fld }}
                    </div>
                {% endfor %}

            </fieldset><br />
        {% endfor %}

        <div id="submit"><input id="submit-btn" type="submit" value="Save"></div>
    </form>
</div>
{% endblock %}

dbe/dbe/templates/issues/comment_form.html
{% extends "issbase.html" %}
{% load todo %}
{% block content %}
<style type="text/css" media="screen">
    #id_body { width: 600px; height: 450px; }
    #container { border: none; }
    #submit { padding-top: 8px; }
</style>

<div class="main">
    <form action="" method="POST">{% csrf_token %}
        {{ modelform.body }}
        <div id="submit"><input id="submit-btn" type="submit" value="Save"></div>
    </form>
</div>
{% endblock %}

dbe/dbe/templates/issues/issbase.html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <title>{% block title %}IssuesApp{% endblock %}</title>
    <link rel="stylesheet" href="/media/css/issues.css" type="text/css" media="screen" charset="utf-8" />
    {% block extrahead %}{% endblock %}
</head>

<body>

    <!-- SIDEBAR -->
    <div id="sidebar"> {% block sidebar %}{% endblock %} </div>

    <div id="container">

        <!-- MENU -->

        <div id="menu">
            {% block nav-global %}
                <h3>IssuesApp</h3>
                <a href="{% url 'admin:issues_issue_changelist' %}">Issues</a>
                <a href="{% url 'add_issues' %}">Add New Issues</a>
            {% endblock %}
        </div>

        <!-- CONTENT -->

        <div id="content">
            {% block content %}{% endblock %}
        </div>
    </div>

</body>
</html>

dbe/dbe/templates/issues/issue_form.html
{% extends "issbase.html" %}
{% load issues %}
{% block content %}
<style type="text/css" media="screen">
    #id_body { width: 600px; height: 250px; }
</style>
<div class="main">
    <form action="" method="POST">{% csrf_token %}
        <fieldset class="module aligned">

        {% for name in modelform.fldorder %}
            {% with modelform|get:name as fld %}
                <div class="form-row">
                    <label class="{% if fld.field.required %} required {% endif %}">{{ fld.label }}</label>
                    {{ fld }}
                </div>
            {% endwith %}
        {% endfor %}

        </fieldset>
        <div id="submit"><input id="submit-btn" type="submit" value="Save"></div>
    </form>
</div>
{% endblock %}

dbe/dbe/templates/issues/progress.html
<div id="progress_cont_{{ pk }}" class="progress_cont">
    <div id="{{ pk }}" class="progress_btns">
        <ul>
            <li>0</li>
            <li>10</li>
            <li>20</li>
            <li>30</li>
            <li>40</li>
            <li>50</li>
            <li>60</li>
            <li>70</li>
            <li>80</li>
            <li>90</li>
            <li>100</li>
        </ul>
    </div>
    <div id="progress_on_{{ pk }}" class="progress_on">&nbsp;</div>
</div>